### ISSUE TITLE
Incorrect Status in parallel process.

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#15]
Hi,

I wanna set up a monitoring software based on O2XFS in parallel with existing application that use XFS manager without O2XFS (Some third part application).

When that application run it runs it's own process for example KT2_SIU_XFS30.exe
and when i use my O2XFS based monitoring it make another KT2_SIU_XFS30.exe even with same user login.The problem is some device like SIU return different status to each process and the first process that run has the correct status and the others will get hardware error on fwDevice and same thing with other statuses.

In Addition the third party application does not lock the hardware, i tested this situation with the test tools that open and register devices instead of third party application and same thing happened.

Is there any way to use existing and running process and preventing running another instance of same process?
Or Is there Any solution for this problem ?

With best regards,
Pouya Moradian

**Comment by AndreasFagschlunger** [comment]
Hi!
For me it sounds like a Service Provider problem, the XFS System is intendend to allow multiple sessions. I know cases where there are three XFS sessions open at the same time, three different processes, all three randomly querying status - one maintenance application, one for monitoring and one for the customers.

So if you say the first process wins, if you start monitoring (O2Xfs) and then third-party app - and monitoring works, but third-party app get's errors - it's in my eyes a misbehavior of the Service Provider - or the XFS Manager. Can you contact support of your XFS provider about this?

The major vendors I know (Diebold, NCR, Wincor Nixdorf) are working fine with concurrent XFS sessions.

I currently see no workaround which would not break XFS if only one process is allowed to query for status and two or more processes should be served.

Another thing to mention, the XFS API defines functions to lock specific devices. It may be possible the third party app locks devices - what happens if two instances of your monitoring application are running without the third-party application? Is still only the first working?

Best regards,
Andreas Fagschlunger

**Comment by pouyamoradian** [comment]
Hi,
Thank you for your reply,
The first answer is yes, the first process wins and the third party applications get incorrect statuses,I think I have to contact with the XFS provider.

As i mentioned the third party applications does not lock the devices, as I tested this situation with test tools and our monitoring agent (these app both dose not lock devices), same story has happened, only first process wins and got correct status.
The tested XFS manager was GWI and KT.

With best regards,
Pouya Moradian

**Comment by pouyamoradian** [comment]
Hello again,

I found that if you run your application as a windows service it could not use existing process for each SP ,but if you run the same code as an executable jar file it uses the existing process and does not run a duplicate process.

Do you have any idea about it?

**Comment by AndreasFagschlunger** [comment]
In my opinion the XFS Manager/SPI is in charge here, O2Xfs always runs in a JVM and doesn't start any other processes (Service Provider, etc.). The JVM accesses the XFS API over JNI - these are standard DLL calls. The XFS Manager delegates the XFS Requests to the Service Providers, also over DLLs from the Service Providers. Either the XFS Manager or the Service Provider decides to start a process, but O2Xfs doesn't create any process.

**Comment by pouyamoradian** [comment]
Thanks for your reply.
