### ISSUE TITLE
Converting WFSResult to LPUSHORT (Question)

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#20]
Hi @AndreasFagschlunger,

Again i have a question,
as you know we will get WFSResult that incluede a pointer (that can be get via getResults function and point) to returned data in fireIntermediateEvent, but in some cases like WFS_EXEE_CIM_INPUTREFUSE  event we have to cast this value to USHORT.
Whats the best way to convert Pointer to USHORT type?
Should I create a class with a class field with type of USHORT like other wfs... types and handle this with assign buffer in constructor?

with Regards,
Pouya

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian!

The specification says the Event Param is LPUSHORT, so WFSResult's lpBuffer is a Pointer to USHORT. So something like this should do the trick:

    public USHORT(Pointer p) {
        this();
        assignBuffer(p);
    }

    WFSResult wfsResult ...
    USHORT value = new USHORT(wfsResult.getResults());

But since the result is a XFS constant, try XfsWord like in CamService:

https://github.com/AndreasFagschlunger/O2Xfs/blob/master/at.o2xfs.xfs.service/src/at/o2xfs/xfs/service/cam/CamService.java#L51

Best regards,
Billie
