### ISSUE TITLE
ZeroTerminatorList Question

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#21]
Dear Andreas,

I've asked you about Zero-Terminated List some week ago, now I've developed ZTList as below:

package at.o2xfs.win32;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * <code>ZTList</code>
 * 
 * A class representing a Zero-terminated list of pointers.
 * 
 * @author Pouya Moradian
 */

public class ZTList<E extends NumberType> extends Type implements Iterable<Pointer>{

	private final List<Pointer> pointers = new ArrayList<Pointer>();

	public <T extends Type> ZTList(List<T> types) {
		for (int i = 0; i < types.size(); i++) {
			pointers.add(new Pointer());
		}
		allocate();
		int offset = 0;
		for (int i = 0; i < types.size(); i++) {
			
			Pointer p = pointers.get(i);
			p.assignBuffer(getBuffer().subBuffer(offset, p.getSize()));
			p.pointTo(types.get(i));
			offset += p.getSize();
		}
	}

	public ZTList(Pointer pointer,E TerminatorValue) {
		int offset = 0;
		Buffer buffer = null;
		while (true) {
			buffer = pointer.buffer(offset + pointer.getSize());
			Pointer p = new Pointer(buffer.subBuffer(offset, pointer.getSize()));
			if (p.equals(TerminatorValue)) {
				break;
			}
			pointers.add(p);
			offset += p.getSize();
		}
		assignBuffer(buffer);
	}
	
	public int getLength(E TerminatorValue){
		
		int size = 0;
		
		for (Pointer p : this) {
			if (p.equals(TerminatorValue))
				break;
			size++;
		}
		return size;
	}
	
	@Override
	public int getSize() {
		int size = Pointer.NULL.getSize();
		for (Pointer p : pointers) {
			size += p.getSize();
		}
		return size;
	}

	@Override
	public Iterator<Pointer> iterator() {
		return pointers.iterator();
	}
}

the problem is the p.equals(TerminatorValue) never happens and whiles goes infinite,
I'm using USHORT type with terminator value of USHORT(0),
Do you have any suggestion?

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

Glad to hear from you again, I don't know if you noticed but there is now a develop-branch where I've added support for CDM XFS 3.xx. Shortly I will publish an update of O²Xfs Operator where you can dispense and present cash.

Back to your question, there already exists a at.o2xfs.win32.ZList class:
https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/at.o2xfs.win32/src/main/java/at/o2xfs/win32/ZList.java

I don't see why you allow TerminatorValue to be a parameter and that's exactly the problem I think. At the moment your ZTList has a list of Pointer-Types, since ZT indicates a "zero-terminated" value the TerminatorValue should always be a [NULL-Pointer](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/at.o2xfs.win32/src/main/java/at/o2xfs/win32/Pointer.java#L42). So the problem I see is you're using USHORT as a terminator. You're checking a Pointer for equality with USHORT, which will always return false, since they are not the same type.

You could compare by value (at.o2xfs.win32.Type.getBytes()), which is the default behavior of Type class equals-Method - Pointer overwrites this default behavior. But in case of UShort this is also likely to fail because a Pointer has at least 4 Bytes and UShort 2 Bytes.

Best regards,
Andreas

**Comment by pouyamoradian** [comment]
Dear @AndreasFagschlunger 

Thank you for your description,
As you know i want to add this NoteIDs as below :
" lpusNoteIDs
Pointer to a zero-terminated list of unsigned shorts which contains the note IDs of the
banknotes the cash-in cash unit or recycle cash unit can take. This field only applies to
WFS_CIM_CITYPINDIVIDUAL cassette types. If there are no note IDs defined for the
cassette or the cassette is not defined as WFS_CIM_CITYPINDIVIDUAL then lpusNoteIDs
will contain NULL. "

I saw zero terminated list of pointer and I put ZTList (zero terminated type) for this and also accept a terminator value for zero representation of Ushort, short, ... because it is a generic type.

But as I understand know i should check Null for termination value, even it is zero terminated.
is it right?

so whats the difference between zero terminated and null terminated ?

Thanks for your good news about CDM module but our deadline is really close.

**Comment by AndreasFagschlunger** [comment]
Hello @pouyamoradian 

Now I know what's the goal behind ZTList. First of all, there is not really a difference between NULL-terminated and zero-terminated, both indicate that the value is 0. Where in case of a Pointer type this means it points to address 0, which is commonly referenced as NULL-Pointer. So the term "NULL-terminated" only applies to Pointer types.

Second, besides Strings this zero-terminated lists are rare but they also occurred in the CDM 3.x spec, e.g. XFS 3.30 CWA 16926-5 WFS_CMD_CDM_SYNCHRONIZE_COMMAND which has WFSCDMSYNCHRONIZECOMMAND as input parameter. My solution was to create a helper class [SynchronizableCommands](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs330/java/at/o2xfs/xfs/cdm/v3_30/SynchronizableCommands.java) which converts from java to zero-terminated list and vice versa, see for [SynchronizeCommand3_30.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs330/java/at/o2xfs/xfs/cdm/v3_30/SynchronizeCommand3_30.java) how SynchronizableCommands is used.

Third, please see the following commit 02040c6228625bff13e10bc8e4e2e19ec032096b where I tried to do the same thing with CashInType3-Structure. Note that the NoteIDs-class can be shared between structures, so your CIM CashIn structure can use it as well.

With best regards,
Andreas

**Comment by pouyamoradian** [comment]
Hello again @AndreasFagschlunger 

Thanks for your clear description, there were no way to covert buffer to UNIT in previous version of WIN32 package, but now I've added new constructor to UINT,USHORT,... for buffer type.

I'm using old version of O2XFS and i'll move to new version soon.

With Best Regards,
Pouya

**Comment by pouyamoradian** [comment]
Hello @AndreasFagschlunger 

I'm Again on the LPUSHORT in WFS_CMD_CIM_CONFIGURE_NOTETYPES,
I've created the noteIds class as:

public class CIMNoteIds extends Type {

	private final USHORT[] noteIDs;

	public CIMNoteIds(int[] noteIDs) {
		this.noteIDs = new USHORT[noteIDs.length];
		allocate();
		set(noteIDs);
	}

	public void set(int[] value) {

		for (int i = 0; i < noteIDs.length; i++) {
			noteIDs[i] = new USHORT();
			noteIDs[i].allocate();

			noteIDs[i].put(value[i]);
		}
	}

	public CIMNoteIds(Pointer aPointer) {

		USHORT temp = new USHORT();
		temp.allocate();

		if (Pointer.NULL.equals(aPointer)) {
			noteIDs = new USHORT[0];
		} else {
			Buffer buffer = null;
			for (int i = 0;; i++) {
				buffer = aPointer.buffer((i * temp.getSize()) + temp.getSize());
				Buffer subBuffer = buffer.subBuffer(i * temp.getSize(),
						temp.getSize());
				USHORT uShort = new USHORT(subBuffer);
				if (uShort.intValue() == 0L) {
					noteIDs = new USHORT[i];
					assignBuffer(buffer);
					break;
				}
			}
		}
	}

	public int[] getArray() {
		int result[] = new int[noteIDs.length];
		for (int i = 0; i < noteIDs.length; i++) {
			result[i] = noteIDs[i].intValue();
		}
		return result;
	}

	@Override
	public int getSize() {

		USHORT tempData = new USHORT();
		tempData.allocate();

		return noteIDs.length == 0 ? 0 : tempData.getSize()
				+ (noteIDs.length * tempData.getSize());
	}
}

I'm using it in this way:

CIMNoteIds temp = new CIMNoteIds(command.noteIds);

Pointer p = new Pointer();
p.allocate();
p.pointTo(temp);
				
XfsExecuteCommandCallUtil.call(cimService,	CIMExecuteCommand.CONFIGURE_NOTETYPES, p, answer,true);

But all i get is WFS_ERR_UNSUPP_DATA !

I've also tested a ZList that point to a list of USHORT and ZTList that i've developed befor with type of USHORT but it does not works.

Do you have any idea?

with regards,
Pouya Moradian

**Comment by AndreasFagschlunger** [comment]
Hy Pouya!

I've found some Bug in my NoteIDs class, so I did a commit with bugfix and unit tests. Please see for yourself:

https://github.com/AndreasFagschlunger/O2Xfs/commit/5797c84189acec4e5c90a9ee33b5cf8dbb08b228

Now I've tested your class as well, and the problem is as the error code states the data is valid but not supported. You're actually passing a array of 0 values, which in this case represents a empty list. Why that?

The `int[]` constructor doesn't assign sub-buffers. What you do in your `int[]` constructor is, you `allocate()` memory for `(noteIDs.length + 1) * sizeof(USHORT)`, that's correct. So the buffer of your `CIMNoteIds` class points the the right amount of memory.

But here comes the problem, you never actually assign values to that memory. In your `set` method you call `allocate()` for each `USHORT`, so you basically reserve a new block of memory (`malloc`) with a whole new address.

Fun fact, it work's from the Java point of view since `getArray` reads the values for each `USHORT`. But the native part get's the address of the memory allocated by `CIMNoteIds`, not the address of each individual `USHORT`.

So what you have to do is, assign the buffer already allocated by `CIMNoteIds` to your `USHORT`'s. Here's what I've changed:

```java
	@Override
	protected void assignBuffer(Buffer aBuffer) {
		super.assignBuffer(aBuffer);
		for (int i = 0; i < noteIDs.length; i++) {
			noteIDs[i] = new USHORT(getBuffer().subBuffer(i * USHORT.SIZE, USHORT.SIZE));
		}
	}

	public void set(int[] value) {
		for (int i = 0; i < noteIDs.length; i++) {
			noteIDs[i].put(value[i]);
		}
	}
```
The `assignBuffer(Buffer)` method is called immediately after memory allocation occurred in `allocate()`. We overwrite the method in `CIMNoteIds` to assign each `USHORT` a part of our whole `CIMNoteIds` memory. By calling `subBuffer(int, int)` method we get a new Buffer object which uses already allocated memory. So the `USHORT`'s point the a memory within the memory of `CIMNoteIds` and not as before to a memory outside of `CIMNoteIds` which is never available to the native part.

**WARNING** Don't forget to call `super.assignBuffer(aBuffer)`, if you forget your `CIMNoteIds` class doesn't have a buffer assigned and will throw exceptions if you try to read/write to the classes `Buffer` instance.

**Comment by pouyamoradian** [comment]
Hi @AndreasFagschlunger 

First of all thank you for your kindly support, 
after that command.noteIds object contain an int array that hold the noteids so my array is not empty but I've got the point, that's right my USHORT values will not pass to O2 dll and the dll just see the value of assigned buffer.
I also test the new code and it works fine,
again thank you.

Best regards,
Pouya Moradian
