### ISSUE TITLE
Connection lost question

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#23]
Hi @AndreasFagschlunger 

I wanna ask a question about XFS Error message WFS_ERR_CONNECTION_LOST,
I'm getting this some time and i don't have any idea  what it is for.
Do you have any idea?

Best Regards,
Pouya

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

As far as I know the WFS_ERR_CONNECTION_LOST occurs if the XFS Manager (msxfs.dll) lost connection to the specified service provder, e.g. the SPI process crashed. Since the problem should be related to the SPI, other XFS applications should also receive these error. I would check the log files from XFS Manager and SP. Maybe the XFS Manager fires a system event (e.g. SOFTWARE_ERROR) with more details.

Best regards,
Andreas Fagschlunger

**Comment by pouyamoradian** [comment]
Dear @AndreasFagschlunger 

I got it,
thank you

best regards,
Pouya Moradian
