### ISSUE TITLE
at.o2xfs.emv.demo.DemoException: No card found

### ISSUE THREAD

**Issue by louiedecastro** [AndreasFagschlunger/O2Xfs#36]
TerminalFactory.getDefault().terminals().list(); from SmartCardIoReader.java class returns [] or empty list.

Exception in thread "main" at.o2xfs.emv.demo.DemoException: at.o2xfs.emv.demo.DemoException: No card found.
	at at.o2xfs.emv.demo.POSDemo.createIcReader(POSDemo.java:132)
	at at.o2xfs.emv.demo.POSDemo.doDemo(POSDemo.java:75)
	at at.o2xfs.emv.demo.POSDemo.main(POSDemo.java:156)
Caused by: at.o2xfs.emv.demo.DemoException: No card found.
	at at.o2xfs.emv.demo.icc.SmartCardIoReader.init(SmartCardIoReader.java:77)
	at at.o2xfs.emv.demo.icc.SmartCardIoReader.<init>(SmartCardIoReader.java:55)

**Comment by AndreasFagschlunger** [comment]
Hi @louiedecastro 

This Exception means Java couldn't find a card reader. The `SmartCardIoReader` class uses the Java standard packages `javax.smartcardio` for accessing card readers. You need to attach a card reader with PC/SC driver installed. Or at least a card reader providing CT-API driver, in this case you could try `CTAPI_ICReader` instead of `SmartCardIoReader`.

**Comment by louiedecastro** [comment]
Thanks for the quick response Andreas. I'm new to XFS and I'm wondering if you have sample or demo using the WFS_CMD_IDC_CHIP_IO/CHIP_POWER to process EMV instead. The device I have right now doesn't have PC/SC driver.

**Comment by AndreasFagschlunger** [comment]
I did this a while ago and have to search for the code. You can start by your own by a class implementing `ICReader` and in the `reset()` method you execute `ReadCardCommand` and/or WFS_CMD_IDC_CHIP_POWER. It depends on your target system. In ICReader's `transmit` method you execute `ChipIOCommand`s. It should work for test purposes.

**Comment by louiedecastro** [comment]
Thanks Andreas! I will try your suggestion. But if you happen to found your code for this I would appreciate if would share it here. It will help other developers too.

**Comment by AndreasFagschlunger** [comment]
As you can see I added the code [here](http://andreasfagschlunger.github.io/O2Xfs/tutorial.html). What's missing is a call to XfsServiceManager#initalize (and shutdown). Please take a look and keep me informed about your progress.

**Comment by louiedecastro** [comment]
Hi Andreas, I was able to make XFS work with EMV kernel as you directed. Thanks for the help.

This maybe another topic but I'll post it here. 
For CVM online auth. Demo is not calling UI to enter PIN and the Online Authorization is returning null.

**Comment by AndreasFagschlunger** [comment]
Hi @louiedecastro! That is because Online PIN authentication is something completely different. You need a payment service provider to communicate with. You payment service provider specifies which keys you need for generating a PIN block. So the process of requesting keys and loading them into the PIN Pad depends highly on your payment service provider. Also how the authorization message looks like depends on your payment system provider (e.g. which EMV fields are mandatory).

So you can for sure use O²Xfs EMV to process online transactions and I did it myself once in an test environment. But the whole host communication is proprietary and can't be simply simulated.
