### ISSUE TITLE
IFD (Interface Device Serial Number) parameter missing in pos.properties

### ISSUE THREAD

**Issue by louiedecastro** [AndreasFagschlunger/O2Xfs#37]
Is there a way to parameter the (IFD) Serial Number in startup?

**Comment by AndreasFagschlunger** [comment]
Hi @louiedecastro 

Currently there is no way to specify EMV Tag 9F1E "Interface Device (IFD) Serial Number" in the Properties. The properties which could be set are needed during the transaction processing, since 9F1E isn't mentioned anywhere I assume it's a informal field only. So if you need this Tag for your online authorization request message, just add it there since the Kernel or card will probably not use them. If I am wrong please tell me so.

I try to explain a little more detailed what I mean. For online authorization you usually first generate an authorization request message according to ISO 8583 standard. Take a look at [jPos](http://jpos.org/). The DE 55 field (ICC Data) is reserved for EMV data. So in your implementation of at.o2xfs.emv.EMVTransactionCallback.doSendAuthorisationRequest() you obtain the necessary data from EMVTransaction and place the outcome in the DE 55 field. The EMV Tags needed may depend on your payment system provider, but here you find a basic example of how to build the value for the DE 55 field:

```java
	private byte[] buildIccSystemRelatedData() {
		final String method = "buildIccSystemRelatedData()";
		ByteArrayBuilder builder = new ByteArrayBuilder();
		for (EMVTag emvTag : tags()) {
			Tag tag = emvTag.getTag();
			if (!transaction.containsData(emvTag)) {
				LOG.warn(method, "Tag not found: " + emvTag);
				continue;
			}
			builder.append(TLVBuilder.newPrimitive(tag, transaction.getMandatoryData(emvTag)).getBytes());
		}
		return builder.build();
	}

	public List<EMVTag> tags() {
		List<EMVTag> result = new ArrayList<EMVTag>();
		result.add(EMVTag.APPLICATION_INTERCHANGE_PROFILE);
		result.add(EMVTag.DEDICATED_FILE_NAME);
		result.add(EMVTag.TERMINAL_VERIFICATION_RESULTS);
		result.add(EMVTag.TRANSACTION_DATE);
		result.add(EMVTag.TRANSACTION_TYPE);
		result.add(EMVTag.TRANSACTION_CURRENCY_CODE);
		result.add(EMVTag.AMOUNT_AUTHORISED_NUMERIC);
		result.add(EMVTag.ISSUER_APPLICATION_DATA);
		result.add(EMVTag.TERMINAL_COUNTRY_CODE);
		result.add(EMVTag.APPLICATION_CRYPTOGRAM);
		result.add(EMVTag.CRYPTOGRAM_INFORMATION_DATA);
		result.add(EMVTag.TERMINAL_CAPABILITIES);
		result.add(EMVTag.CARDHOLDER_VERIFICATION_METHOD_RESULTS);
		result.add(EMVTag.TERMINAL_TYPE);
		result.add(EMVTag.APPLICATION_TRANSACTION_COUNTER);
		result.add(EMVTag.UNPREDICTABLE_NUMBER);
		return result;
	}
```

And as I mentioned earlier, this would be the place where you add your "Interface Device (IFD) Serial Number".

If you send a authorization request message, you will receive an authorization response message. The ARPC (Authorization Response Code) and value of the DE 55 field (form response) is then used to build the AuthorisationResponse Object. The EMV Kernel then decides if the transaction is approved or declined. If the authorization is approved, you will send a financial advice message. You have to build the value for DE 55 again, including the Issuer Script results (at.o2xfs.emv.EMVTransaction.getIssuerScriptResults()) so your payment system provider knows if they where executed properly. At this point the EMV transaction is completed.
