### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no at.o2xfs.win32 in java.library.path

### ISSUE THREAD

**Issue by azdafirmansyah** [AndreasFagschlunger/O2Xfs#39]
Hi , I new in  XFS.  Glad to know that java can communicate with XFS.

When we look into class, we found System.loadLibrary("at.o2xfs.win32");

but after try test class found this error : 
 java.lang.UnsatisfiedLinkError: no at.o2xfs.win32 in java.library.path. 

Any suggest why I got this error ?

Thanks

Regards,
Azda Firmansyah

**Comment by AndreasFagschlunger** [comment]
Hello @azdafirmansyah 

Please make sure you checkout the develop-Branch, since a lot have changed there. I soon will rebase the develop branch onto master. The develop-Branch already features a CI-Build using AppVeyor, So take a look at the `appveyor.yml` to see how a full build works.

You now also don't have to build the native libraries if you don't want to. The build scripts for the native artifacts are located in separated files (build-native.gradle). The CI-Build-Server builds this native libraries, puts them into a JAR file and publishes them to a public maven repository (https://repo.fagschlunger.co.at/libs-snapshot-local). The java build (build.gradle) is retrieving the native artifacts as normal (maven-)dependencies.

I also changed the way libraries are loaded, because native artifacts are now contained in JAR files. There is a new utility class `Library` which locates the native libraries using the classpath and extracts them into your users default directory (.o2xfs-directory). SWT (Standard Widget Toolkit) from eclipse uses this technique.

There is also a GitHub-Pages site for this project: http://andreasfagschlunger.github.io/O2Xfs/

But as the time of writing it may be a little outdated, so best check `appveyor.yml`.

Let me now if you manged to get O²Xfs Up & Running or need further assistance.

Best regards,
Andreas Fagschlunger

**Comment by azdafirmansyah** [comment]
Hi @AndreasFagschlunger,

I got following error when execute gradlew build  :  
:at.o2xfs.operator:check UP-TO-DATE
:at.o2xfs.operator:build
:at.o2xfs.win32:assemble
:at.o2xfs.win32:compileTestJava
:at.o2xfs.win32:processTestResources NO-SOURCE
:at.o2xfs.win32:testClasses
:at.o2xfs.win32:test

at.o2xfs.win32.BOOLTest > testFalse FAILED
    java.lang.UnsatisfiedLinkError at BOOLTest.java:45

at.o2xfs.win32.BOOLTest > testTrue FAILED
    java.lang.NoClassDefFoundError at BOOLTest.java:39

at.o2xfs.win32.impl.Win32BufferTest > putAndGet FAILED
    java.lang.NoClassDefFoundError at Win32BufferTest.java:46

at.o2xfs.win32.impl.Win32BufferTest > subBuffer FAILED
    java.lang.NoClassDefFoundError at Win32BufferTest.java:67

at.o2xfs.win32.impl.Win32BufferTest > bufferOverflow FAILED
    java.lang.Exception
        Caused by: java.lang.NoClassDefFoundError at Win32BufferTest.java:54

at.o2xfs.win32.ZSTRTest > helloWorld FAILED
    java.lang.NoClassDefFoundError at ZSTRTest.java:38

9 tests completed, 6 failed
:at.o2xfs.win32:test FAILED

Regards,
Azda Firmansyah

**Comment by AndreasFagschlunger** [comment]
The UnsatisfiedLinkError may be the cause. Is it possible that gradle runs on a 64 bit JVM? Please ensure gradle uses a x86 runtime by adding a `org.gradle.java.home` property to `gradle.properties` pointing to a x86 JDK, e.g.:

`org.gradle.java.home=C:/Program Files (x86)/Java/jdk1.8.0_51`

You can put a global `gradle.properties` file under the `.gradle` subdirectory in you user directory.

**Comment by azdafirmansyah** [comment]
@AndreasFagschlunger , Thanks it's work
