### ISSUE TITLE
Run on Windows 10 64 bit

### ISSUE THREAD

**Issue by minhngvan** [AndreasFagschlunger/O2Xfs#88]
Can I run XFS on Windows 10 64 bit?

**Comment by AndreasFagschlunger** [comment]
If you have a XFS Manager (msxfs.dll) compiled with 64 bit yes. Unfortunately the XFS manager shipped with the SDK (https://www.cen.eu/work/sectors/digital_society/pages/wsxfs.aspx) only comes with a x86/32-bit DLL.
I know some vendors did their own implementation of the msxfs.dll, but I don't know of any vendor who already uses 64 bit. And I don't think this changes in near future, since most drivers are still compiled with 32 bit.
Also, https://adoptopenjdk.net/ offers latest Java builds for 32 bit as well, so you could use the latest java features and I don't really see other reasons why someone would need 64 bit to operate XFS.

**Comment by minhngvan** [comment]
Many thanks @AndreasFagschlunger
